version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  # backend:
  #   #image: # тут образ с докерхаба!!
  #   build:
  #     context: ../backend
  #   restart: always
  #   volumes:
  #     - static_value:/app/static/
  #     - media_value:/app/media/
  #   depends_on:
  #     - db
  #   env_file:
  #     - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    restart: always

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      #- backend
      - frontend
    restart: always
      
volumes:
  static_value:
  media_value:

# Проект нужно запустить в трёх контейнерах (nginx, PostgreSQL и Django)
#  (контейнер frontend используется лишь для подготовки файлов)
#   через docker-compose на вашем сервере в Яндекс.Облаке. 
#   Образ с проектом должен быть запушен на Docker Hub.